language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest .
  - coverage run -m pytest
  - coverage report -m code.py
before_install:
  - pip install --user codecov
after_success:
  - codecov
